import { index, pgEnum, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core'

/**
 * `projects` table - per-owner project records.
 *
 *   - `id` is the internal app primary key (UUID v4, generated by Postgres).
 *   - `name` is the human-readable project title.
 *   - `description` is optional free-form text.
 *   - `ownerId` carries the Clerk `user_xxx` id of the project owner;
 *     indexed for fast owner-scoped lookups.
 *   - `status` is a lifecycle enum (`active`, `archived`, `deleted`).
 */
export const projectStatusEnum = pgEnum('project_status', ['active', 'archived', 'deleted'])

export const projects = pgTable(
  'projects',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: text('name').notNull(),
    description: text('description'),
    ownerId: text('owner_id').notNull(),
    status: projectStatusEnum('status').default('active').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    index('projects_owner_id_idx').on(table.ownerId),
    index('projects_name_idx').on(table.name),
  ],
)

export type ProjectRow = typeof projects.$inferSelect
export type ProjectInsert = typeof projects.$inferInsert
