import { index, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core'

/**
 * `users` table — the app-side mirror of the Clerk-owned identity.
 *
 *   - `id` is the internal app primary key (UUID v4, generated by Postgres).
 *   - `clerkUserId` carries the `user_xxx` id Clerk assigns; UNIQUE + indexed
 *     so the `POST /webhooks/clerk` handler can look up the row in O(1)
 *     on `user.updated` / `user.deleted`.
 *   - `email` is kept here for denormalized convenience (joins, reporting).
 *     Clerk remains the source of truth; changes arrive via webhook.
 *
 * No auth state (password hashes, MFA factors, sessions) lives in this
 * table — Clerk owns all of it.
 */
export const users = pgTable(
  'users',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    clerkUserId: text('clerk_user_id').notNull().unique(),
    email: text('email').notNull(),
    displayName: text('display_name'),
    avatarUrl: text('avatar_url'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    index('users_clerk_user_id_idx').on(table.clerkUserId),
    index('users_email_idx').on(table.email),
  ],
)

export type UserRow = typeof users.$inferSelect
export type UserInsert = typeof users.$inferInsert
